version: '3.7'
services:
  postgresql:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tourism_pass_mgmt

  microservice:
    build: .
    ports:
      - 8080:8080
    volumes:
      - microservice-logs:/opt/lpg/tourism_pass_management_system/logs

volumes:
  postgres-data:
  microservice-logs:
